name: AddAkses
version: 1.0
main: com.example.addakses.AddAkses
api-version: 1.21
commands:
  addakses:
    description: Beri akses sementara ke player
    usage: /addakses <username> <durasi>
    permission: addakses.command
  delakses:
    description: Cabut akses sementara player
    usage: /delakses <username>
    permission: addakses.command
permissions:
  addakses.command:
    description: Izin untuk memberi atau menghapus akses
    default: op
  addakses.temp:
    description: Permission sementara yang diberikan ke player
    default: false
